// <----------------------- Q . 1 ------------------------>

let a=20;
let b=30;
let c=10;
(a>b&&a>c)?console.log("a is greater"):(b>a&&b>c)?console.log("b is greater"):console.log("c is greater")

// <----------------------- Q . 2 ------------------------>

let number=-1;
(number>0)?console.log("number is positive"):(number==0)?console.log("number is uniq"):console.log("number is negitive")

// <----------------------- Q . 3 ------------------------>

let loggedin= true;
(loggedin==true)?console.log("welcome back"):console.log("please login")



// <----------------------- Q . 4 ------------------------>


let dayofweek = "monday";
if(dayofweek= "saturday"){
    console.log("weekend")
}
else if(dayofweek= "sunday"){
    console.log("weekend")
}
else{console.log("not weekend")}